@startuml
hide footbox
participant "File Source" as Client
participant "File Manager" as Server
"Client" -> "Server" : Update DocumentReference Request
activate "Server"
activate "Client"
"Server" --> "Client" : Update DocumentReference Response
deactivate "Server"
deactivate "Client"

@enduml